#!/usr/bin/env python

import sys
import zmq

PUB_HOST = "10.0.3.1"
PUB_PORT = 5552

if (len(sys.argv) > 1):
    if( sys.argv[1] == 'on' ):
        message = "FAN on"
    elif( sys.argv[1] == 'off' ):
        message = "FAN off"
    pub_context = zmq.Context()
    publisher = pub_context.socket (zmq.PUB)
    pub_address = "tcp://%s:%d" % (PUB_HOST, PUB_PORT)
    publisher.bind (pub_address)

    publisher.send(message)
