#!/usr/bin/env python

import zmq
import time

from tinkerforge.ip_connection import IPConnection
from tinkerforge.bricklet_analog_out import AnalogOut

from daemon import runner

BRICK_HOST = "localhost"
BRICK_PORT = 4223
BRICK_UID = "9mL" # UID of analog out bricklet

SUB_HOST = "10.0.3.36" # aggregator
SUB_PORT = 5555

class FanController():
    def __init__(self):
        self.stdin_path = '/dev/null'
        self.stdout_path = '/dev/tty'
        self.stderr_path = '/dev/tty'
        self.pidfile_path =  '/tmp/sam-fand.pid'
        self.pidfile_timeout = 5

    def run(self):
        brick_ipcon = IPConnection(BRICK_HOST, BRICK_PORT) # Create IP connection to brickd
        brick_fan = AnalogOut(BRICK_UID) # Create device object
        brick_ipcon.add_device(brick_fan) # Add device to IP connection

        sub_context = zmq.Context()
        subscriber = sub_context.socket (zmq.SUB)
        sub_address = "tcp://%s:%d" % (SUB_HOST, SUB_PORT)
        subscriber.connect (sub_address)
        subscriber.setsockopt (zmq.SUBSCRIBE, "FAN")

        # daemon loop
        while True:
            message = subscriber.recv()
            if (message == "FAN on"):
                brick_fan.set_voltage(3300)
            elif (message == "FAN off"):
                brick_fan.set_voltage(0)


app = FanController()
daemon_runner = runner.DaemonRunner(app)
daemon_runner.do_action()
